### ISSUE TITLE
HIGH Snyk severity in dependency, update elliptic to 6.6.1

### ISSUE THREAD

**Issue by aumetov** [Brightspace/node-jwk-to-pem#192]
Improper Verification of Cryptographic Signature has High security severity score in snyk reports _8.7_
Affecting elliptic package, versions <6.6.0

https://security.snyk.io/vuln/SNYK-JS-ELLIPTIC-8187303
Need to upgrade elliptic package to latest version 6.6.1

**Comment by manpreet-compro** [comment]
Yes, flagged by AWS inspector also in my case
Elliptic has fixed this - https://github.com/indutny/elliptic/issues/325

Could we upgrade the package and release new version

**Comment by omsmith** [comment]
jwk-to-pem's constraint on elliptic already matched the updated version.

However, I've release 2.0.7 should that help your teams with your scanners.

Consider moving your usage away from jwk-to-pem to modern Node.js features: https://github.com/Brightspace/node-jwk-to-pem/issues/187#issuecomment-2271203531
