### ISSUE TITLE
in example where does token come from?

### ISSUE THREAD

**Issue by itayo** [Brightspace/node-jwk-to-pem#23]

**Comment by j3parker** [comment]
That's up to you.

This library is for converting JWK (JSON web keys) to PEM format.

JWKs are often used to sign JWTs (JSON web tokens), but that's a topic outside of this library.

**Comment by itayo** [comment]
But in your example code it is undefined

**Comment by omsmith** [comment]
Apologies if the example is confusing. I wanted to provide context in how you might use the library, but the _jsonwebtoken_ library and token parts aren't strictly related.

You might read more about JWTs with the following resources:
- https://tools.ietf.org/html/rfc7519
- https://jwt.io/
