### ISSUE TITLE
Public Key vs RSA Public Key

### ISSUE THREAD

**Issue by venkatmarepalli** [Brightspace/node-jwk-to-pem#24]
I found this Golang library online https://play.golang.org/p/wr7dwBB_hs

My JWT Token signature is getting validated when I use the public key generated by the above golang routine but it is not getting validated when I use the pem generated by this library (I am using jwt.io to do the signature validation). When I debugged the key I found that the golang library has some extra string in the pem key. Can you throw some light on this, Why is there a difference ?

There is an extra `MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8A` in the GoLang method. 

```
Key generated using this library
------------BEGIN PUBLIC KEY-----
MIIBCgKCAQEAtVKUtcx/n9rt5afY/2WFNvU6PlFMggCatsZ3l4RjKxH0jgdLq6CS
cb0P3ZGXYbPzXvmmLiWZizpb+h0

Key generated by GoLang.
------------BEGIN PUBLIC KEY-----
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAtVKUtcx/n9rt5afY/2WF
NvU6PlFMggCatsZ3l4RjKxH0jgdLq6CScb0P3ZGXYbPzXvmmLiWZizpb+h0qup5j
```

**Comment by jonsalvas** [comment]
Exactly the same issue on my side but with keycloak. The public key from keycloak contains an additional string that is not contained the pem generated by this library.

**Comment by omsmith** [comment]
This sounds like a difference between PKCS#1 and PKCS#8, or something to that effect. jwt.io may not support PKCS#1, or it may have to pass additional options to its libraries to specify it.

Are you having trouble actually using these PEMs in a production situation (such as with openssl, or node `crypto`)?

**Comment by venkatmarepalli** [comment]
We are using https://github.com/SkyLothar/lua-resty-jwt library which does the jwt validations. The JWT token's signature doesn't get validated by this library or jwt.io without the extra key string in the beginning. I have to hard code and add it to get it working. We don't use node crypto or openssl.

**Comment by omsmith** [comment]
Realize this has been a while now, but I decided to revisit this issue this evening. I have a PR open which moves all pem output to PKCS#8.

If you could try it out and make sure it works for you, that would be swell.
