### ISSUE TITLE
Elliptic Timing Attack

### ISSUE THREAD

**Issue by awatson1978** [Brightspace/node-jwk-to-pem#33]
Hello,
We're using `node-jwk-to-pem` in one of our projects, and Linux Community Bridge is reporting a Timing Attack based on it's `elliptic` dependency, which we've traced to `node-jwk-to-pem`.  It's recommended to upgrade to version `6.5.2` or higher.  

![Screen Shot 2019-12-04 at 12 42 03 PM](https://user-images.githubusercontent.com/675910/70171175-cc312d80-1693-11ea-94ae-ea13d768a5e1.png)

Thanks for looking at this.

**Comment by j3parker** [comment]
I merged the patch from #32 to address this. Thank you for the report!
