### ISSUE TITLE
Support OID as crv for EC JWK

### ISSUE THREAD

**Issue by Sayan751** [Brightspace/node-jwk-to-pem#34]
Thank you for this awesome package.

I think it would be nice to support the oid string as value for the `crv` property in EC type jwk. So both the following examples are supported.

```javascript
jwkToPem({kty: 'EC', crv: 'P-256', x: '...', y: '...'});
jwkToPem({kty: 'EC', crv: '1.2.840.10045.3.1.7', x: '...', y: '...'});
```

I see that you are already mapping the friendly names to oids. A possible solution might be to add aliases for the same.

**Comment by omsmith** [comment]
Hi Sayan

The friendly names in question are those defined by the [JOSE IANA Registry](https://www.iana.org/assignments/jose/jose.xhtml). A JWK with the OID listed as the crv would be non-standard, and I don't think that's something I'm looking to support.

Thank you though. I appreciate you making the suggestion.
