### ISSUE TITLE
private key support (ES256)

### ISSUE THREAD

**Issue by focusaurus** [Brightspace/node-jwk-to-pem#5]
Would you consider accepting an ES256 JWK as input and returning a PEM private key? The format I'm thinking of for the jwk would be:

    {
        alg: 'ES256',
        crv: 'P-256',
        kty: 'EC',
        d: 'base64url-encoded-private-key-d-value-blah'
    }

**Comment by omsmith** [comment]
Hey @focusaurus, thanks for reaching out

I could see supporting private keys for sure - it makes sense, just wasn't part of our first slice. I would want to be explicit about it (to avoid _accidently_ sending off a private key unknowingly).

With that in mind, would the following make sense to you (also @jopnick)?

```js
var jwkToPem = require('jwk-to-pem');

var publicPem = jwkToPem({
    alg: 'ES256',
    crv: 'P-256',
    kty: 'EC',
    x: '...',
    y: '...',
    d: 'base64url-encoded-private-key-d-value-blah'
});

var privatePem = jwkToPem({
    alg: 'ES256',
    crv: 'P-256',
    kty: 'EC',
    x: '...',
    y: '...',
    d: 'base64url-encoded-private-key-d-value-blah'
}, { private: true });

// The following will throw an error, as a private pem can't be constructed
var privatePem = jwkToPem({
    alg: 'ES256',
    crv: 'P-256',
    kty: 'EC',
    x: '...',
    y: '...'
}, { private: true });
```

**Comment by focusaurus** [comment]
Seems reasonable to me.

**Comment by jbdatko** [comment]
@omsmith +1 for this feature.

Where I would find this very helpful is in testing. Hopefully in production cases, you are right, care should be given to handling private keys.

But when trying to test JWK across different programming languages, it'd would be very nice to generate JWKs, export them as PEM such that other openssl libraries can suck them in.

**Comment by jopnick** [comment]
I like explicitness so as to not leak private keys. Sounds pretty good.

**Comment by omsmith** [comment]
Published as _v1.2.0_

**Comment by focusaurus** [comment]
Confirmed working well for me in v1.2.0. :cake: :pizza: :bow:
