### ISSUE TITLE
Security Patch for Elliptic 6.5.3 -> 6.5.4

### ISSUE THREAD

**Issue by cnnranderson** [Brightspace/node-jwk-to-pem#76]
I can create an MR if necessary. Looks like we're seeing a red flag here via Snyk and should be an easy dependency update :)

**Comment by daradoro** [comment]
Hello! is this being worked on? Currently getting flagged by yarn audit :(

**Comment by peterdenham** [comment]
Also getting flagged here. Not sure of the protocol for contributing to this repo, but I went ahead and opened a PR here: https://github.com/Brightspace/node-jwk-to-pem/pull/84

**Comment by Piccirello** [comment]
@j3parker @omsmith Could either of you weigh in on this?

**Comment by j3parker** [comment]
Released as [v2.0.5](https://github.com/Brightspace/node-jwk-to-pem/releases/tag/v2.0.5).
